// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'IconFileIcons:electron': typeof import('~icons/file-icons/electron')['default']
    'IconFluent:maximize20Filled': typeof import('~icons/fluent/maximize20-filled')['default']
    'IconIc:baselineClose': typeof import('~icons/ic/baseline-close')['default']
    'IconIon:minusRound': typeof import('~icons/ion/minus-round')['default']
    'IconTwemoji:boar': typeof import('~icons/twemoji/boar')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NInput: typeof import('naive-ui')['NInput']
    NSpace: typeof import('naive-ui')['NSpace']
  }
}

export { }
